## Append samples of your project ##
resources:
- infrastructure_v1beta1_nvidiabmmcluster.yaml
- infrastructure_v1beta1_nvidiabmmmachine.yaml
- infrastructure_v1beta1_nvidiabmmmachinetemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
